### ISSUE TITLE
Introduce a rule for too high NBANDS

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/custodian#224]
When modeling very small systems (e.g. a single CO molecule in a box) with VASP, if `NBANDS` is too large, the electronic structure (e.g. the DOS) can be completely unphysical. I found this out the hard way when, by default, running a single node job on Cori caused `NBANDS = 64` yet I was modeling a CO molecule where `NBANDS = 6` might be more appropriate. In the former case, countless fictitious states were introduced into the DOS.

We should introduce some sort of rule that makes sure `NBANDS` isn't too high for small systems.

Brainstorming with @mkhorton yields the following possible rule:
if NBANDS > 2\*default NBANDS where default NBANDS is max(NELECT/2+NIONS/2, 0.6*NELECT), then kill job and restart with the default unless `LOPTICS = .TRUE.`, in which case use a factor of 10 as the cutoff.

**Comment by arosen93** [comment]
@utf, alternatively this could be something we incorporate into `atomate2` directly. That could be easier, but I could see arguments for both approaches.

**Comment by utf** [comment]
I agree with @shyuep that this should be in custodian. However I would add a caveat that if NBANDS is already in the INCAR then it shouldn't be overwritten.

**Comment by yang-ruoxi** [comment]
Note that VASP will also automatically changes NBANDS depending on the nodes/cores you are running with, so it may not necessarily be a problem with atomate or custodian : [link](https://www.vasp.at/wiki/index.php/NBANDS) 
" When executed on multiple CPUs, VASP automatically increases the number of bands, so that NBANDS is divisible by the number of CPU cores. If [NCORE](https://www.vasp.at/wiki/index.php/NCORE) > 1, NBANDS is increased until it is divisible by the number of cores in a group ([NCORE](https://www.vasp.at/wiki/index.php/NCORE)). If [KPAR](https://www.vasp.at/wiki/index.php/KPAR) > 1, NBANDS is increased until it is divisible by the number of cores in a group."

**Comment by arosen93** [comment]
@yang-ruoxi --- actually that's the problem I ran into. The issue is if you take a small molecule like CO and run on a full KNL node, VASP will automatically change NBANDS to be too large and when you have an excess number of bands, the results can be nonphysical as in my prior example.

**Comment by arosen93** [comment]
@yang-ruoxi: I have confirmed that even if the user changes NBANDS in the INCAR, VASP will still override it (see attached).

With this in mind, I think the best course of action if for Custodian to simply issue a warning to the user if the total number of cores is greater than the _actual_ NBANDS value (i.e. `grep -r 'NBANDS=' OUTCAR`). One could think about potentially raising an unfixable error if, for instance, the actual NBANDS value is much (e.g. 2x) greater than the number of cores, but this would be arbitrary and it's not clear what value would be best. At the very least, I think a warning should be provided.

Unfortunately, I was not able to come up with a clean way of doing this because the `VaspErrorHandler` is looking for VASP-reported errors and not ones that aren't reported but that we detect. I'll let someone else take the lead on this if they feel so inclined.

**Comment by Andrew-S-Rosen** [comment]
Just noting here that this will be an even bigger problem for CPU nodes on Perlmutter, which have 128 cores.
