### ISSUE TITLE
Example not working - serialisation issue? 

### ISSUE THREAD

**Issue by jan-janssen** [materialsproject/custodian#55]
Hi, 

I tried the example from your website but was not successful, so I looked into the unit tests and updated the example correspondingly, but still I have some issues with the serialisation. 
ExampleJob:
```
class ExampleJob(Job):

    def __init__(self, jobid, params=None):
        if params is None:
            params = {"initial": 0, "total": 0}
        self.jobid = jobid
        self.params = params

    def setup(self):
        self.params["initial"] = 0
        self.params["total"] = 0

    def run(self):
        sequence = [random.uniform(0, 1) for i in range(100)]
        self.params["total"] = self.params["initial"] + sum(sequence)

    def postprocess(self):
        pass

    @property
    def name(self):
        return "ExampleJob{}".format(self.jobid)
```

Error Handler: 
```
class ExampleHandler(ErrorHandler):

    def __init__(self, params):
        self.params = params

    def check(self):
        return self.params["total"] < 50

    def correct(self):
        self.params["initial"] += 1
        return {"errors": "total < 50", "actions": "increment by 1"}
```

This works: 
```
njobs = 100
params = {"initial": 0, "total": 0}
c = Custodian([ExampleHandler(params)],
              [ExampleJob(i, params) for i in range(njobs)],
               max_errors=njobs)
output = c.run()
```

This does not: 
```
njobs = 100
c = Custodian([ExampleHandler({"initial": 0, "total": 0})],
              [ExampleJob(i, {"initial": 0, "total": 0}) for i in range(njobs)],
               max_errors=njobs)
output = c.run()
```

**Comment by shyuep** [comment]
Thanks. I have updated the examples. The reason why it works in the first case but not in the second is that in the first case, you are passing the same dictionary to the handler and the job. In te second, the Job and Handler have different dicts.

**Comment by jan-janssen** [comment]
Thanks, is this also the reason why the output is always the same? 

```
job': {'@class': 'ExampleJob',
   '@module': '__main__',
   'jobid': 1,
   'params': {'initial': 0, 'total': 58.02235053149143}}
```

```
'job': {'@class': 'ExampleJob',
   '@module': '__main__',
   'jobid': 2,
   'params': {'initial': 0, 'total': 58.02235053149143}}
```

For me it would be nice if the parameters in the json file would reflect the actual parameters of the specific job, but that does not seem to be the case.

**Comment by shyuep** [comment]
Yes. That's the reason. 

In general, the json file should store the actual parameters of the job. A proper way of coding this example would be to do a defensive copy of whatever params is passed to the ExampleJob, e.g., `self.params = dict(params)`, a separate variable is used to hold the current total, and the ExampleHandler reads the current value from the job from a file written by the job rather than passing a common dict between them. That way, the json will always reflect the actual value being passed in. 

So this example violates a few good coding practices. i. mutable default arguments are a bad idea. ii. having two separate classes modify the same param variable. I only wrote the example this way to avoid having to write to file and read back from file for a simple example.
