### ISSUE TITLE
Mac OS package needs update on conda

### ISSUE THREAD

**Issue by specter119** [materialsproject/custodian#74]
The latest version is still 1.1.0 for [Mac OS](https://anaconda.org/matsci/custodian) on [matsci channel](https://anaconda.org/matsci/repo).

**Comment by shyuep** [comment]
Just updated and released new version. In general, I don't bother to update custodian for MacOS because most of the time, custodian is only used on Linux based clusters.

**Comment by specter119** [comment]
@shyuep Yes, I see, but it's also a dependency for atomate. I think we should loose the requirement against custodian.

**Comment by shyuep** [comment]
Well, generally atomate does not run on Mac either.


Shyue Ping

On March 10, 2018 at 7:19:40 PM, KeLiu (notifications@github.com) wrote:

@shyuep <https://github.com/shyuep> Yes, I see, but it's also a dependency
for atomate. I think we should loose the requirement against custodian.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/materialsproject/custodian/issues/74#issuecomment-372086189>,
or mute the thread

**Comment by computron** [comment]
People definitely want to install atomate locally - e.g I submit all my atomate workflows from my Mac and also use atomate to connect to the database after the runs. It is just the run part itself that I dont do on the Mac (although someone could, especially if we integrate a code like qchem in the future)

**Comment by shyuep** [comment]
@computron I would then put custodian as an optional dependency that is necessary only if you are actually RUNNING jobs.

**Comment by computron** [comment]
If custodian really doesn't want to support Mac, I can do the optional dependency for atomate, but it's a pain for users - we'll have to tell people in the installation instructions that they need to manually install custodian as a second step otherwise they will get errors upon trying to run the job. Note also that apart from VASP, many types of calculations could indeed be run locally on a Mac. e.g., we run qchem locally sometimes. We often run Boltztrap locally (there is no custodian for that, but there could be). Could be the same with FEFF, Gaussian, etc.
